---
title: "cluster analysis"
author: "Lee JaeSeo"
date: "2017년 12월 26일"
output: html_document
editor_options: 
  chunk_output_type: console
---


### load data
```{r}
protein <- read.table("./Data/protein.txt", sep="\t", header = TRUE)
head(protein)
```

```{r}
summary(protein) ##range가 너무 넓다 -> normalize

(vars.to.use <- colnames(protein)[-1])
pmatrix <- scale(protein[,vars.to.use])
summary(pmatrix)

## 정규화 한것과 원본 데이터 비교
head(protein)
summary(pmatrix)
sd(as.matrix(protein[,vars.to.use]))
sd(pmatrix)

## scale 함수로 정규화 한 데이터를 원본으로 돌리기 위해 저장
( pcenter <- attr(pmatrix, "scaled:center") )
( pscale <- attr(pmatrix, "scaled:scale") )


## clustering
( d <- dist(pmatrix, method="euclidean") )
( pfit <- hclust(d, method="ward.D") )

## draw
plot(pfit, labels=protein$Country)
rect.hclust(pfit, k=5)


( groups <- cutree(pfit, k=5) )
print_clusters <- function(labels, k) {
  for(i in 1:k) {
    print(paste("cluster", i))
    print(protein[labels==i, c("Country", "RedMeat", "Fish", "Fr.Veg")])
  }
}
print_clusters(groups, 5)
```

### ggplot을 이용한 시각화
```{r}
library(ggplot2)
```

```{r}
( princ <- prcomp(pmatrix) ) ## 9개 변수가 9개 주성분으로 나눠짐
nComp <- 2 ## 주성분 개수 2개만 사용
project <- predict(princ, newdata=pmatrix)[,1:nComp]
project.plus <- cbind(as.data.frame(project), cluster=as.factor(groups), country=protein$Country)
ggplot(project.plus, aes(PC1, PC2)) +
  geom_point(aes(shape=cluster)) +
  geom_text(aes(label=country), hjust=0, vjust=1)
```

### 클러스터의 부트스트랩 평가
```{r}
library(fpc)
```

```{r}
kbest.p <- 5
cboot.hclust <- clusterboot(pmatrix, clustermethod=hclustCBI, method="ward.D", k=kbest.p) ##console에 몇개 만들어졌는지 띄워진다.
summary(cboot.hclust$result)
groups <- cboot.hclust$result$partition
print_clusters(groups, kbest.p)

cboot.hclust$bootmean ##각 클러스터의 평균
cboot.hclust$bootbrd ##각 클러스터의 개수
```

<br>
<br>

### 클러스터 개수 설정하기
```{r}
library(reshape2)
```

```{r}
sqr_edist <- function(x, y){
  sum((x-y)^2)
}

wss.cluster <- function(clustermat) {
  c0 <- apply(clustermat, 2, FUN=mean)
  sum(apply(clustermat, 1, FUN=function(row){sqr_edist(row, c0)}))
}

wss.total <- function(dmatrix, labels) {
  wsstot <- 0
  k <- length(unique(labels))
  for(i in 1:k) wsstot <- wsstot + wss.cluster(subset(dmatrix, labels==i))
  wsstot
}

totss <- function(dmatrix) {
  grandmean <- apply(dmatrix, 2, mean)
  sum(apply(dmatrix, 1, function(row){sqr_edist(row, grandmean)}))
}

ch_criterion <- function(dmatrix, kmax, method="kmeans") {
  if(!(method %in% c("kmeans", "hclust"))){
    stop("method must be one of c(keans', 'hclust')")
  }
  npts <- dim(dmatrix)[1] # 행의 수
  
  totss <- totss(dmatrix)
  
  wss <- numeric(kmax)
  crit <- numeric(kmax)
  wss[1] <- (npts-1)*sum(apply(dmatrix, 2, var))
  for(k in 2:kmax) {
    if(method=="kmeans") {
      clustering <- kmeans(dmatrix, k, nstart=10, iter.max=100)
      wss[k] <- clustering$tot.withinss
    } else { # hclust
      d <- dist(dmatrix, method="euclidean")
      pfit <- hclust(d, method="ward.D")
      labels <- cutree(pfit, k=k)
      wss[k] <- wss.total(dmatrix, labels)
    }
  }
  bss <- totss-wss
  crit.num <- bss/(0:(kmax-1))
  crit.denom <- wss/(npts-1:kmax)
  list(crit=crit.num/crit.denom, wss=wss, totss=totss)
}

clustcrit <- ch_criterion(pmatrix, 10, method="hclust")
critframe <- data.frame(k=1:10, ch=scale(clustcrit$crit), wss=scale(clustcrit$wss))
critframe <- melt(critframe, id.vars=c("k"), variable.name="measure", value.name="score")
ggplot(critframe, aes(x=k, y=score, color=measure)) + 
  geom_point(aes(shape=measure)) + geom_line(aes(linetype=measure)) +
  scale_x_continuous(breaks=1:10, labels=1:10)
```



<br>
<br>

# k-means clustering

```{r}
pclusters <- kmeans(pmatrix, kbest.p, nstart=100, iter.max=100)
summary(pclusters)
pclusters$centers 
pclusters$size # 각 클러스터의 개수

( groups <- pclusters$cluster )
print_clusters(groups, kbest.p)
clustering.ch <- kmeansruns(pmatrix, krange=1:10, criterion="ch")
clustering.asw <- kmeansruns(pmatrix, krange=1:10, criterion="asw")
clustering.ch$bestk
clustering.asw$bestk
clustering.ch$crit
clustering.asw$crit


critframe <- data.frame(k=1:10, ch=scale(clustering.ch$crit), asw=scale(clustering.asw$crit))
critframe <- melt(critframe, id.vars=c("k"), variable.name = "measure", value.name="score")
ggplot(critframe, aes(x=k, y=score, color=measure)) +
  geom_point(aes(shape=measure)) +
  geom_line(aes(linetype=measure)) +
  scale_x_continuous(breaks=1:10, labels=1:10)
summary(clustering.ch)
```







