---
title: "Classification with spamdatabase"
author: "Lee JaeSeo"
date: "2017년 12월 27일"
output: html_document
editor_options: 
  chunk_output_type: console
---

# classification

```{r}
spamD <- read.table("./Data/spamD.txt", header=T, sep="\t")
head(spamD)
spamTrain <- subset(spamD, spamD$rgroup>=10)
spamTest <- subset(spamD, spamD$rgroup<10)
spamVars <- setdiff(colnames(spamD), list('rgroup', 'spam'))
```

```{r}
spamFormula <- as.formula(paste('spam=="spam"', paste(spamVars, collapse=' + '), sep= ' ~ '))
spamModel <- glm(spamFormula, family=binomial(link='logit'), data=spamTrain)
spamTrain$pred <- predict(spamModel, newdata=spamTrain, type='response')
spamTest$pred <- predict(spamModel, newdata=spamTest, type='response')
print(with(spamTest, table(y=spam, glmPred=pred>0.5)))
```


# Decision Tree
```{r}
library(rpart)
library(rpart.plot)
```

```{r}
tModel <- rpart(Species~Sepal.Length+Sepal.Width+Petal.Length+Petal.Width, data=iris)
tModel
rpart.plot(tModel)
```


# KNN

```{r}
head(iris)
table(iris$Species)
summary(iris)
```

```{r}
#install.packages("ggvis")
library(ggvis)

iris %>% ggvis(~Petal.Length, ~Petal.Width, fill=~factor(Species)) %>% layer_points()

## scale 함수가 아닌 min을 0으로 max를 1로 정규화
min_Max_normalizer <- function(x) {
  num <- x-min(x)
  denom <- max(x)-min(x)
  return(num/denom)
}
normalized_iris <- as.data.frame(lapply(iris[1:4], min_Max_normalizer))
summary(normalized_iris)

## training/test dataset 분할
set.seed(1234)
random_sample <- sample(2, nrow(iris), replace=TRUE, prob=c(0.67, 0.33))
iris.training <- iris[random_sample==1, 1:4]
nrow(iris.training)
iris.test <- iris[random_sample==2, 1:4]
iris.trainLabels <- iris[random_sample==1, 5]
iris.testLabels <- iris[random_sample==2, 5]
```


```{r}
# install.packages("class")
library(class)
iris_Model <- knn(train=iris.training, test=iris.test, cl=iris.trainLabels, k=3)

# install.packages("gmodels")
library(gmodels)
CrossTable(x=iris.testLabels, y=iris_Model, expected=T, prop.c=F, prop.r=F, prop.t=F, prop.chisq=F)

#k-means
kmean_iris <- iris
kmean_iris$Species <- NULL
( clusters <- kmeans(kmean_iris, 3) )
table(iris$Species, clusters$cluster)

plot(kmean_iris[c("Sepal.Length", "Sepal.Width")],
     col=clusters$cluster, pch=c(15,16,17)[as.numeric(clusters$cluster)])
```

<br>
<br>

# RandomForest
```{r}
# install.packages(c("randomForest", "caret", "e1071", "ROCR"))

library(randomForest)
library(caret)
library(e1071)
library(ROCR)

# source("performance_plot_utils.R")

data_F <- spamD
```

```{r}
formula.init <- as.formula("spam~.")
rf_Model <- randomForest(formula.init, data=data_F, importance=T, proximity=T)
print(rf_Model)
test.class.var <- data_F[,58]

rf.prediction <- predict(rf_Model, type="class")

confusionMatrix(data=rf.prediction, reference=test.class.var, positive=NULL)
```








